# Generated by Django 3.0.4 on 2020-03-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Probad', '0002_auto_20200320_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chondokotha',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Probad.Category'),
        ),
        migrations.AlterField(
            model_name='chondokotha',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Probad.District'),
        ),
    ]
