# Generated by Django 3.0.4 on 2020-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Probad', '0004_place_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chondokotha',
            name='category',
        ),
        migrations.AddField(
            model_name='chondokotha',
            name='category',
            field=models.ManyToManyField(to='Probad.Category'),
        ),
    ]
